config/routes.rb
Shopper::Application.routes.draw do

  root :to => 'high_voltage/pages#show', :id => 'home'

  devise_for :users
  resources :users do
    resources :lists
  end
  
  resources :lists do
    resources :items
  end
  
  resources :items

  
  
  

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :brand, :description, :name, :note, :quantity, :unit, :list_id
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :user_id
  belongs_to :user
  has_many :items, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :lists_attributes 
  # attr_accessible :title, :body
  
  has_many :lists, :dependent => :destroy
#  accepts_nested_attributes_for :lists, :allow_destroy => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_list_id
  
  # GET /items
  # GET /items.json
  def index
    @items = @list.items.all

    respond_to do |format|
      #format.html # index.html.erb
      format.html { redirect_to list_items_url(@list), :action => 'show' }
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = @list.items.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = @list.items.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = @list.items.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = @list.items.new(params[:item])
    
    respond_to do |format|
      if @item.save
        format.html { redirect_to list_path(@list), notice: 'Item was successfully created.' }
        #format.html { redirect_to list_items_url(@list), notice: 'Item was successfully created.' }
#        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
#        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = @list.items.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to [@list, @item], notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    Item.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to list_path(@list) }
      #format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
  
  private 
    def get_list_id
       @list = List.find(params[:list_id])
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_currentuser_id
  
  # GET /lists
  # GET /lists.json
  def index
    @lists = @user.lists.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = @user.lists.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = @user.lists.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = @user.lists.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = @user.lists.new(params[:list])

    respond_to do |format|
      if @list.save
        #format.html { redirect_to :action => "show", :id => @list.id }
        format.html { redirect_to user_lists_url(@user) }
        #format.html { redirect_to [@user, @list], notice: 'List was successfully created.' }
        format.json { render json: [@user, @list], status: :created, location: [@user, @list] }
      else
        format.html { render action: "new" }
#        format.json { render json: @user.list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = @user.lists.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to [@user, @list], notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    List.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to user_lists_url(@user) }
      format.json { head :no_content }
    end
  end
  
  
  
  private
    def get_currentuser_id
      @user = current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.erb
<%= form_for([@list, @item]) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :brand %><br />
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :unit %><br />
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', :back %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Brand</th>
    <th>Quantity</th>
    <th>Unit</th>
    <th>Note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td><%= item.description %></td>
    <td><%= item.brand %></td>
    <td><%= item.quantity %></td>
    <td><%= item.unit %></td>
    <td><%= item.note %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/items/show.html.erb
<div class="ui-bar ui-bar-b">
    <p id="notice"><%= notice %></p>
</div>
<ol data-role="listview">
	<li>Name: <%= @item.name %> </li>
	<li>Description: <%= @item.description %> </li>
	<li>Brand: <%= @item.brand %> </li>
	<li>Quantity: <%= @item.quantity %> </li>
	<li>Unit:<%= @item.unit %> </li>
	<li>Note:<%= @item.note %> </li>
	<li>Caterory:<%= @item.category %></li>
</ol>

<p><%= link_to 'Edit Item', edit_list_item_path(@list), "data-role" => "button", "data-inline" => "true" %><%= link_to 'Shopping Lists', user_lists_path(current_user), "data-role" => "button", "data-inline" => "true" %><%= link_to 'Item List', list_path(@list), "data-role" => "button", "data-inline" => "true" %><%= link_to 'Delete', { :action => "destroy", :id => @item.id }, :method => :delete, "data-role" => "button", "data-inline" => "true"  %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	
	<meta charset="utf-8" />
	  <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame 
	       Remove this if you use the .htaccess -->
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Family Shopper</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body/>
	<div>
		<%= yield %>
	</div>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for([@user, @list]) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', [@user, @list] %> |
<%= link_to 'Back', @user %>

app/views/lists/index.html bak.erb
<ul data-role="listview" data-filter="true" data-filter-placeholder="Search lists..." data-inset="true" data-icon="delete">
	<% @user.lists.each do |list| %>
    <li><%= link_to list.name, user_list_path(@user, list.id)  %><%= link_to 'Delete', { :action => "destroy", :id => list.id }, :method => :delete %></li>
	<% end %>
</ul>

<br />
<p><%= link_to 'New List', new_user_list_url(@user) , "data-role" => "button", "data-inline" => "true" %></p>
	
<div id="user_nav">
	<p id="header_notice"><%= notice %></p>
	<% if user_signed_in? %>
	 		<p>Logged in as: <strong><%= current_user.email %></strong></p>
			<%= link_to 'Edit profile', edit_user_registration_path %>   |
			<%= link_to("Logout", destroy_user_session_path, :method => :delete ) %>
	<% else %>
			<%= link_to "Sign up", new_user_registration_path %>   | 
			<%= link_to "Login", new_user_session_path %>
	<% end %>
</div>

app/views/lists/index.html.erb
<ul data-role="listview" data-filter="true" data-filter-placeholder="Search lists..." data-inset="true" data-icon="delete">
	<% @user.lists.each do |list| %>
    <li><%= link_to list.name, user_list_path(@user, list.id)  %><%= link_to 'Delete', { :action => "destroy", :id => list.id }, :method => :delete %></li>
	<% end %>
</ul>

<p><%= link_to 'New List', new_user_list_url(@user) , "data-role" => "button", "data-inline" => "true" %></p>
	
<div id="user_nav">
	<p id="header_notice"><%= notice %></p>
	<% if user_signed_in? %>
	 		<p>Logged in as: <strong><%= current_user.email %></strong></p>
			<%= link_to 'Edit profile', edit_user_registration_path %>   |
			<%= link_to("Logout", destroy_user_session_path, :method => :delete ) %>
	<% else %>
			<%= link_to "Sign up", new_user_registration_path %>   | 
			<%= link_to "Login", new_user_session_path %>
	<% end %>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/lists/show.html.erb
<div class="ui-bar ui-bar-b">
    <p id="notice"><%= notice %></p>
</div>

<ul data-role="listview" data-inset="true" data-icon="delete">
	  <li>Name: <%= @list.name %></li>  
</ul>

<ul data-role="listview" data-inset="true" data-icon="delete" data-filter="true" data-filter-placeholder="Search items...">
		<% @list.items.each do |item|%>
	  		<li><%= link_to item.name, list_item_path(@list, item.id) %></li> 
		<%end%>
</ul>

<p><%= link_to 'Edit List Name', edit_user_list_path(@user), "data-role" => "button", "data-inline" => "true" %><%= link_to 'Shopping Lists', user_lists_path(current_user), "data-role" => "button", "data-inline" => "true" %><%= link_to 'Add Item', new_list_item_url(@list, @item), "data-role" => "button", "data-inline" => "true" %></p>

app/views/pages/home.html.erb
<h1>Welcome to Shopper!</h1>
<div id="user_nav">
	<p id="header_notice"><%= notice %></p>
	<% if user_signed_in? %>
	 		<p>Logged in as: <strong><%= current_user.email %></strong></p>
			<%= link_to 'Edit profile', edit_user_registration_path %>   |
			<%= link_to("Logout", destroy_user_session_path, :method => :delete ) %>
			<p><%= link_to 'Shopping Lists', user_lists_path(current_user) %></p>

	<% else %>
			<%= link_to "Sign up", new_user_registration_path %>   | 
			<%= link_to "Login", new_user_session_path %>
	<% end %>
</div>